title: "SFO Editor Database"
remote_theme: just-the-docs/just-the-docs

logo: "/assets/image/logo_db.png"

# Aux links for the upper right navigation
aux_links:
  "SFO Save Editor":
    - "https://github.com/thezodiacox0/sfo-editor-database"

callouts:
  blue:
    title: "ğŸ› ï¸ Info"
    color: "blue"
  purple:
    title: "ğŸ› ï¸ Important"
    color: "purple"
  yellow:
    title: "ğŸ› ï¸ Warning"
    color: "yellow"
  red:
    title: "ğŸ› ï¸ Caution"
    color: "red"
  green:
    title: "ğŸ› ï¸ TIP"
    color: "green"
  notes:
    title: "ğŸ“ Notes"
    color: "grey-dk"
  white:
    title: "ğŸ› ï¸ Text"
    color: "grey-lt"
    
# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release.
# Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2025 <a href=\"https://github.com/thezodiacox0\">TheZodiacoX</a>. <a href=\"https://github.com/thezodiacox0/sfo-editor-database/tree/master/LICENSE\">GPL-3.0 license</a>"

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/thezodiacox0/sfo-editor-database" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
